# Generated by Django 6.0.2 on 2026-05-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short notification title.', max_length=200, verbose_name='title')),
                ('body', models.TextField(blank=True, help_text='Full notification message body.', verbose_name='body')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='True once the user has viewed the notification.', verbose_name='is read')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this notification was created.', verbose_name='created at')),
                ('recipient', models.ForeignKey(help_text='The user who receives this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='recipient')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx')],
            },
        ),
    ]
