# Generated by Django 6.0.2 on 2026-05-02 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Grade name, e.g. "Grade 10".', max_length=50, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'grade',
                'verbose_name_plural': 'grades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'announcement',
                'verbose_name_plural': 'announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subjects', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'subject',
                'verbose_name_plural': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='title')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the subject.', verbose_name='order')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.grade', verbose_name='grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.subject', verbose_name='subject')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='title')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', verbose_name='video URL')),
                ('video_file', models.FileField(blank=True, help_text='Uploaded video file (optional alternative to URL).', null=True, upload_to='topic_videos/', verbose_name='video file')),
                ('explanation', models.TextField(blank=True, verbose_name='explanation')),
                ('example', models.TextField(blank=True, verbose_name='example')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.module', verbose_name='module')),
            ],
            options={
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True, verbose_name='watched at')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watches', to=settings.AUTH_USER_MODEL, verbose_name='student')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='courses.topic', verbose_name='topic')),
            ],
            options={
                'verbose_name': 'video watch',
                'verbose_name_plural': 'video watches',
                'ordering': ['-watched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['subject', 'grade'], name='module_subject_grade_idx'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['module', 'order'], name='topic_module_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='videowatch',
            unique_together={('student', 'topic')},
        ),
    ]
