import React, { createContext, useContext, useState } from 'react'

export type Lang = 'en' | 'ru' | 'kz'

const translations = {
  en: {
    // Landing
    landing_tagline: 'Modern Learning System',
    landing_hero_title1: 'Learn smarter.',
    landing_hero_title2: 'Grow faster.',
    landing_hero_desc: 'A complete platform for students and teachers: video lessons, quizzes, assignments, community, progress tracking and smooth screen demonstrations.',
    landing_go_dashboard: 'My Dashboard →',
    landing_signin: 'Sign In',
    landing_activate: 'Activate Account',
    landing_start_free: 'Get started free →',
    landing_stats_subjects: 'Subjects',
    landing_stats_subjects_sub: 'All levels',
    landing_stats_videos: 'Video Lessons',
    landing_stats_videos_sub: 'HD quality',
    landing_stats_quizzes: 'Quizzes',
    landing_stats_quizzes_sub: 'Instant result',
    landing_stats_students: 'Students',
    landing_stats_students_sub: 'Growing every day',
    landing_features_title: 'Everything you need to learn',
    landing_features_sub: 'A modern system built for real progress',
    landing_how_title: 'How it works',
    landing_how_sub: 'Just three simple steps',
    landing_testimonials_title: 'What our users say',
    landing_cta_title: 'Ready to start learning?',
    landing_cta_desc: 'Ask your teacher or admin to create an account — and activate it in 30 seconds',
    landing_cta_btn: 'Activate account →',
    landing_footer: '© 2026 MLS Learning Platform. All rights reserved.',
    landing_in_action: 'MLS in action',
    landing_in_action_sub: 'Scroll — images expand and create a beautiful funnel effect',
    landing_immerse: 'Immerse yourself in MLS',
    landing_immerse_sub: 'Scroll down — the platform interface comes alive into an interactive story',
    landing_student_dash: 'Student Dashboard',
    landing_video_lesson: 'Video Lesson',
    landing_community: 'MLS Community',
    landing_today_solved: 'Solved a tough problem today!',
    landing_who_passed: 'Who already finished the algebra module?',
    landing_thanks: 'Thanks for the help with geometry!',
    landing_progress: '87% progress',
    landing_quiz_after: 'Quiz after lesson',
    landing_assignment: 'Assignment',
    landing_ready_learn: 'Ready to learn?',
    landing_ask_teacher: 'Ask your teacher or admin to create an account — activate it in 30 seconds',

    // Features
    feature_video_title: 'Video Lessons',
    feature_video_desc: 'Watch high-quality lessons at your own pace, anytime and anywhere.',
    feature_quiz_title: 'Quizzes',
    feature_quiz_desc: 'Test your knowledge after each lesson with instant feedback.',
    feature_assignments_title: 'Assignments',
    feature_assignments_desc: 'Submit your work as a photo and get feedback from your teacher.',
    feature_community_title: 'Community',
    feature_community_desc: 'Share progress, ask questions and motivate each other.',
    feature_progress_title: 'Progress Tracking',
    feature_progress_desc: 'See your scores, completed modules and overall progress.',
    feature_teachers_title: 'Expert Teachers',
    feature_teachers_desc: 'Learn from experienced teachers with structured curricula.',

    // Steps
    step1_title: 'Get registered',
    step1_desc: 'An admin or teacher creates your account and sends you the login.',
    step2_title: 'Activate account',
    step2_desc: 'Enter your phone number and create a password — account is live.',
    step3_title: 'Start learning',
    step3_desc: 'Open subjects, watch videos, pass quizzes and submit assignments.',

    // Nav labels
    nav_home: 'Home',
    nav_subjects: 'Subjects',
    nav_assignments: 'Assignments',
    nav_feed: 'Feed',
    nav_chat: 'Chat',
    nav_meetings: 'Meetings',
    nav_profile: 'Profile',
    nav_dashboard: 'Dashboard',
    nav_content: 'Content',
    nav_quizzes: 'Quizzes',
    nav_submissions: 'Submissions',
    nav_students: 'Students',
    nav_announcements: 'Announcements',

    // Sidebar descriptions
    desc_home: 'Dashboard overview',
    desc_subjects: 'Explore learning paths',
    desc_assignments: 'Tasks and submissions',
    desc_feed: 'Community updates',
    desc_chat: 'Messages and support',
    desc_meetings: 'Classes and calls',
    desc_profile: 'Your personal space',

    // Auth
    signin_title: 'Sign in',
    signin_subtitle: 'Welcome back! Enter your credentials to continue learning.',
    signin_phone_label: 'Phone number or email',
    signin_pass_label: 'Password',
    signin_btn: 'Sign in',
    signin_loading: 'Signing in...',
    signin_first_time: 'First time? Activate account →',
    signin_no_account: 'No account yet?',
    signin_activate: 'Activate your account',
    slide1_title: 'Watch video lessons',
    slide1_desc: 'Learn at your own pace with high-quality video content and a smooth adaptive interface.',
    slide2_title: 'Test your knowledge',
    slide2_desc: 'Practice quizzes after every lesson and build strong understanding step by step.',
    slide3_title: 'Track study progress',
    slide3_desc: 'Follow your learning journey with progress tracking, tasks, and feedback from teachers.',

    register_title: 'Activate Account',
    register_subtitle: 'Enter your phone number and set a password to activate your account.',
    register_phone_label: 'Phone number',
    register_pass_label: 'Set password',
    register_btn: 'Activate',
    register_loading: 'Activating...',
    register_already: 'Already activated?',
    register_signin: 'Sign in',
    register_join: 'Join the platform',
    register_rocket_sub: 'Activate your account and start your learning journey right now.',

    // Profile
    profile_title: 'My Profile',
    profile_full_name: 'Full Name',
    profile_phone: 'Phone Number',
    profile_email: 'Email',
    profile_save: 'Save Changes',
    profile_saving: 'Saving...',
    profile_saved: 'Profile updated!',
    profile_upload_photo: 'Upload Photo',
    profile_change_photo: 'Change Photo',
    profile_notifications: 'Notifications',
    profile_no_notif: 'No notifications yet.',
    profile_mark_read: 'Mark read',
    profile_mark_all: 'Mark all read',

    // Teacher
    teacher_panel: 'Teacher Panel',
    teacher_workspace: 'teacher workspace',
    teacher_build: 'Build, manage, teach',
    teacher_elegant: 'Elegant tools for modern teachers.',
    teacher_open_profile: 'Open profile',
    teacher_exit: 'Exit panel',
    teacher_log_out: 'Log out',
    teacher_active_section: 'Active section',
    teacher_premium: 'Premium workspace',
    teacher_smart_flow: 'Smart teaching flow',
    teacher_manage_desc: 'Manage lessons, assignments, students and announcements in one beautiful workspace.',
    teacher_profile_label: 'TEACHER PROFILE',

    // Student
    student_os: 'STUDENT OS',
    student_learn: 'Learn smarter,',
    student_not_louder: 'not louder.',
    student_workspace_desc: 'A premium workspace for studying, submitting tasks, joining meetings and tracking progress.',
    student_current_page: 'CURRENT PAGE',
    student_focus: 'Focus',
    student_focus_val: 'High',
    student_mode: 'Mode',
    student_mode_val: 'Student',
    student_profile_label: 'STUDENT PROFILE',
    student_welcome_back: 'Welcome back',
    student_learning_status: 'Learning Status',
    student_submission_rate: 'Submission success rate based on approved work.',
    student_total_submissions: 'Total Submissions',
    student_approved: 'Approved',
    student_pending: 'Pending',
    student_rejected: 'Rejected',
    student_recent_submissions: 'Recent Submissions',
    student_recent_sub_desc: 'Your latest uploaded assignments and their review status.',
    student_no_submissions: 'No submissions yet.',
    student_profile_role: 'Profile Role',
    student_account: 'Student Account',
    student_profile_role_desc: 'This is your personal learning identity inside the platform. Track progress, submissions, and activity from one place.',
    student_quick_summary: 'Quick Summary',
    student_approved_work: 'Approved work',
    student_pending_review: 'Pending review',
    student_needs_correction: 'Needs correction',
    student_motivation: 'Motivation',
    student_momentum: 'Keep building your momentum',
    student_momentum_desc: 'Every finished submission adds to your academic progress. Stay consistent and keep moving forward.',
    student_recently_submitted: 'Recently submitted',

    // Notifications
    notifications_title: 'Notifications',
    notifications_empty: 'No notifications',
    notifications_mark_all: 'Mark all read',

    // common
    status_approved: 'Approved',
    status_pending: 'Pending',
    status_rejected: 'Rejected',
  },
  ru: {
    landing_tagline: 'Современная Система Обучения',
    landing_hero_title1: 'Учись умнее.',
    landing_hero_title2: 'Расти быстрее.',
    landing_hero_desc: 'Полноценная платформа для учеников и учителей: видео-уроки, квизы, задания, сообщество, трекинг прогресса и плавная демонстрация экрана.',
    landing_go_dashboard: 'Мой дашборд →',
    landing_signin: 'Войти',
    landing_activate: 'Активировать аккаунт',
    landing_start_free: 'Начать бесплатно →',
    landing_stats_subjects: 'Предметы',
    landing_stats_subjects_sub: 'Все уровни',
    landing_stats_videos: 'Видео-уроки',
    landing_stats_videos_sub: 'HD качество',
    landing_stats_quizzes: 'Квизы',
    landing_stats_quizzes_sub: 'Мгновенный результат',
    landing_stats_students: 'Ученики',
    landing_stats_students_sub: 'Растём каждый день',
    landing_features_title: 'Всё, что нужно для обучения',
    landing_features_sub: 'Современная система, созданная для реального прогресса',
    landing_how_title: 'Как это работает',
    landing_how_sub: 'Всего три простых шага',
    landing_testimonials_title: 'Что говорят наши пользователи',
    landing_cta_title: 'Готовы начать учиться?',
    landing_cta_desc: 'Попросите учителя или администратора создать аккаунт — и активируйте его за 30 секунд',
    landing_cta_btn: 'Активировать аккаунт →',
    landing_footer: '© 2026 MLS Learning Platform. Все права защищены.',
    landing_in_action: 'MLS в действии',
    landing_in_action_sub: 'Прокручивай — изображения расширяются и создают красивый воронкообразный эффект',
    landing_immerse: 'Погрузись в MLS',
    landing_immerse_sub: 'Прокручивай вниз — интерфейс платформы оживает и превращается в интерактивное повествование',
    landing_student_dash: 'Дашборд ученика',
    landing_video_lesson: 'Видео-урок',
    landing_community: 'Сообщество MLS',
    landing_today_solved: 'Сегодня решил сложную задачу!',
    landing_who_passed: 'Кто уже прошёл модуль по алгебре?',
    landing_thanks: 'Спасибо за помощь с геометрией!',
    landing_progress: '87% прогресса',
    landing_quiz_after: 'Тест после урока',
    landing_assignment: 'Задание',
    landing_ready_learn: 'Готовы начать?',
    landing_ask_teacher: 'Попросите учителя или администратора создать аккаунт — активируйте за 30 секунд',

    feature_video_title: 'Видео-уроки',
    feature_video_desc: 'Смотрите качественные уроки в своём темпе, в любое время и в любом месте.',
    feature_quiz_title: 'Квизы',
    feature_quiz_desc: 'Проверяйте знания после каждого урока с мгновенной обратной связью.',
    feature_assignments_title: 'Задания',
    feature_assignments_desc: 'Отправляйте работы в виде фото и получайте отзывы от учителя.',
    feature_community_title: 'Сообщество',
    feature_community_desc: 'Делитесь прогрессом, задавайте вопросы и мотивируйте друг друга.',
    feature_progress_title: 'Отслеживание прогресса',
    feature_progress_desc: 'Смотрите оценки, завершённые модули и общий прогресс.',
    feature_teachers_title: 'Опытные учителя',
    feature_teachers_desc: 'Учитесь у опытных преподавателей со структурированными учебными планами.',

    step1_title: 'Пройти регистрацию',
    step1_desc: 'Администратор или учитель создаёт аккаунт и отправляет данные для входа.',
    step2_title: 'Активировать аккаунт',
    step2_desc: 'Введите номер телефона и создайте пароль — аккаунт активирован.',
    step3_title: 'Начать учиться',
    step3_desc: 'Открывайте предметы, смотрите видео, проходите квизы и сдавайте задания.',

    nav_home: 'Главная',
    nav_subjects: 'Предметы',
    nav_assignments: 'Задания',
    nav_feed: 'Лента',
    nav_chat: 'Чат',
    nav_meetings: 'Встречи',
    nav_profile: 'Профиль',
    nav_dashboard: 'Дашборд',
    nav_content: 'Контент',
    nav_quizzes: 'Квизы',
    nav_submissions: 'Работы',
    nav_students: 'Ученики',
    nav_announcements: 'Объявления',

    desc_home: 'Обзор дашборда',
    desc_subjects: 'Изучить учебные пути',
    desc_assignments: 'Задачи и работы',
    desc_feed: 'Новости сообщества',
    desc_chat: 'Сообщения и поддержка',
    desc_meetings: 'Занятия и звонки',
    desc_profile: 'Ваше личное пространство',

    signin_title: 'Войти',
    signin_subtitle: 'С возвращением! Введите данные для продолжения обучения.',
    signin_phone_label: 'Номер телефона или email',
    signin_pass_label: 'Пароль',
    signin_btn: 'Войти',
    signin_loading: 'Вход...',
    signin_first_time: 'Первый раз? Активировать аккаунт →',
    signin_no_account: 'Нет аккаунта?',
    signin_activate: 'Активировать аккаунт',
    slide1_title: 'Смотрите видео-уроки',
    slide1_desc: 'Учитесь в своём темпе с качественным видео-контентом и адаптивным интерфейсом.',
    slide2_title: 'Проверяйте знания',
    slide2_desc: 'Практические квизы после каждого урока помогут закрепить материал.',
    slide3_title: 'Отслеживайте прогресс',
    slide3_desc: 'Следите за своим учебным путём с трекингом прогресса, заданиями и отзывами учителей.',

    register_title: 'Активация аккаунта',
    register_subtitle: 'Введите номер телефона и установите пароль для активации.',
    register_phone_label: 'Номер телефона',
    register_pass_label: 'Установить пароль',
    register_btn: 'Активировать',
    register_loading: 'Активация...',
    register_already: 'Уже активирован?',
    register_signin: 'Войти',
    register_join: 'Присоединяйтесь к платформе',
    register_rocket_sub: 'Активируйте аккаунт и начните учебный путь прямо сейчас.',

    profile_title: 'Мой профиль',
    profile_full_name: 'Полное имя',
    profile_phone: 'Номер телефона',
    profile_email: 'Email',
    profile_save: 'Сохранить изменения',
    profile_saving: 'Сохранение...',
    profile_saved: 'Профиль обновлён!',
    profile_upload_photo: 'Загрузить фото',
    profile_change_photo: 'Изменить фото',
    profile_notifications: 'Уведомления',
    profile_no_notif: 'Уведомлений пока нет.',
    profile_mark_read: 'Отметить прочитанным',
    profile_mark_all: 'Отметить всё прочитанным',

    teacher_panel: 'Панель учителя',
    teacher_workspace: 'рабочее пространство',
    teacher_build: 'Создавай, управляй, учи',
    teacher_elegant: 'Элегантные инструменты для современных учителей.',
    teacher_open_profile: 'Открыть профиль',
    teacher_exit: 'Выйти из панели',
    teacher_log_out: 'Выйти',
    teacher_active_section: 'Активный раздел',
    teacher_premium: 'Премиум рабочее пространство',
    teacher_smart_flow: 'Умный процесс преподавания',
    teacher_manage_desc: 'Управляйте уроками, заданиями, учениками и объявлениями в одном красивом пространстве.',
    teacher_profile_label: 'ПРОФИЛЬ УЧИТЕЛЯ',

    student_os: 'СРЕДА УЧЕНИКА',
    student_learn: 'Учись умнее,',
    student_not_louder: 'а не громче.',
    student_workspace_desc: 'Премиум рабочее пространство для учёбы, сдачи заданий, встреч и отслеживания прогресса.',
    student_current_page: 'ТЕКУЩАЯ СТРАНИЦА',
    student_focus: 'Фокус',
    student_focus_val: 'Высокий',
    student_mode: 'Режим',
    student_mode_val: 'Ученик',
    student_profile_label: 'ПРОФИЛЬ УЧЕНИКА',
    student_welcome_back: 'С возвращением',
    student_learning_status: 'Статус обучения',
    student_submission_rate: 'Процент успешных работ на основе одобренных.',
    student_total_submissions: 'Всего работ',
    student_approved: 'Одобрено',
    student_pending: 'На проверке',
    student_rejected: 'Отклонено',
    student_recent_submissions: 'Последние работы',
    student_recent_sub_desc: 'Ваши последние загруженные задания и их статус проверки.',
    student_no_submissions: 'Работ пока нет.',
    student_profile_role: 'Роль профиля',
    student_account: 'Аккаунт ученика',
    student_profile_role_desc: 'Это ваша личная учебная идентичность на платформе. Отслеживайте прогресс, работы и активность из одного места.',
    student_quick_summary: 'Краткая сводка',
    student_approved_work: 'Одобренные работы',
    student_pending_review: 'На проверке',
    student_needs_correction: 'Требует исправления',
    student_motivation: 'Мотивация',
    student_momentum: 'Продолжай набирать обороты',
    student_momentum_desc: 'Каждая завершённая работа добавляет к вашему академическому прогрессу. Будьте последовательны.',
    student_recently_submitted: 'Недавно отправлено',

    notifications_title: 'Уведомления',
    notifications_empty: 'Нет уведомлений',
    notifications_mark_all: 'Отметить всё прочитанным',

    status_approved: 'Одобрено',
    status_pending: 'На проверке',
    status_rejected: 'Отклонено',
  },
  kz: {
    landing_tagline: 'Заманауи Оқыту Жүйесі',
    landing_hero_title1: 'Ақылдырақ оқы.',
    landing_hero_title2: 'Тезірек өс.',
    landing_hero_desc: 'Оқушылар мен мұғалімдерге арналған толыққанды платформа: бейнесабақтар, тесттер, тапсырмалар, қоғамдастық, прогрес мониторингі.',
    landing_go_dashboard: 'Менің дашбордым →',
    landing_signin: 'Кіру',
    landing_activate: 'Аккаунтты белсендіру',
    landing_start_free: 'Тегін бастау →',
    landing_stats_subjects: 'Пәндер',
    landing_stats_subjects_sub: 'Барлық деңгейлер',
    landing_stats_videos: 'Бейнесабақтар',
    landing_stats_videos_sub: 'HD сапасы',
    landing_stats_quizzes: 'Тесттер',
    landing_stats_quizzes_sub: 'Жылдам нәтиже',
    landing_stats_students: 'Оқушылар',
    landing_stats_students_sub: 'Күн сайын өсіп жатыр',
    landing_features_title: 'Оқу үшін қажет нәрселердің бәрі',
    landing_features_sub: 'Нақты прогреске арналған заманауи жүйе',
    landing_how_title: 'Қалай жұмыс істейді',
    landing_how_sub: 'Тек үш қарапайым қадам',
    landing_testimonials_title: 'Пайдаланушылар не дейді',
    landing_cta_title: 'Оқуды бастауға дайынсыз ба?',
    landing_cta_desc: 'Мұғалімнен немесе әкімшіден аккаунт жасауды сұраңыз — 30 секундта белсендіріңіз',
    landing_cta_btn: 'Аккаунтты белсендіру →',
    landing_footer: '© 2026 MLS Learning Platform. Барлық құқықтар қорғалған.',
    landing_in_action: 'MLS іс жүзінде',
    landing_in_action_sub: 'Айналдырыңыз — суреттер кеңейіп, әдемі воронка эффектін жасайды',
    landing_immerse: 'MLS-ке батыңыз',
    landing_immerse_sub: 'Төмен айналдырыңыз — платформа интерфейсі интерактивті әңгімеге айналады',
    landing_student_dash: 'Оқушы дашборды',
    landing_video_lesson: 'Бейнесабақ',
    landing_community: 'MLS Қоғамдастығы',
    landing_today_solved: 'Бүгін қиын есеп шештім!',
    landing_who_passed: 'Алгебра модулін кім аяқтады?',
    landing_thanks: 'Геометриядағы көмегіңізге рахмет!',
    landing_progress: '87% прогрес',
    landing_quiz_after: 'Сабақтан кейінгі тест',
    landing_assignment: 'Тапсырма',
    landing_ready_learn: 'Бастауға дайынсыз ба?',
    landing_ask_teacher: 'Мұғалімнен аккаунт жасауды сұраңыз — 30 секундта белсендіріңіз',

    feature_video_title: 'Бейнесабақтар',
    feature_video_desc: 'Кез келген уақытта, кез келген жерде сапалы сабақтарды өз қарқынмен тамашалаңыз.',
    feature_quiz_title: 'Тесттер',
    feature_quiz_desc: 'Әр сабақтан кейін жылдам кері байланыспен білімді тексеріңіз.',
    feature_assignments_title: 'Тапсырмалар',
    feature_assignments_desc: 'Жұмысыңызды фото ретінде жіберіп, мұғалімнен пікір алыңыз.',
    feature_community_title: 'Қоғамдастық',
    feature_community_desc: 'Прогреспен бөлісіңіз, сұрақ қойыңыз және бір-біріңізді ынталандырыңыз.',
    feature_progress_title: 'Прогресті бақылау',
    feature_progress_desc: 'Бағаларды, аяқталған модульдерді және жалпы прогресті қараңыз.',
    feature_teachers_title: 'Тәжірибелі мұғалімдер',
    feature_teachers_desc: 'Құрылымдық оқу жоспарлары бар тәжірибелі мұғалімдерден үйреніңіз.',

    step1_title: 'Тіркелу',
    step1_desc: 'Әкімші немесе мұғалім аккаунт жасап, кіру деректерін жібереді.',
    step2_title: 'Аккаунтты белсендіру',
    step2_desc: 'Телефон нөмірін енгізіп, пароль жасаңыз — аккаунт дайын.',
    step3_title: 'Оқуды бастау',
    step3_desc: 'Пәндерді ашыңыз, бейнелерді қараңыз, тесттерден өтіңіз және тапсырмалар тапсырыңыз.',

    nav_home: 'Басты',
    nav_subjects: 'Пәндер',
    nav_assignments: 'Тапсырмалар',
    nav_feed: 'Лента',
    nav_chat: 'Чат',
    nav_meetings: 'Кездесулер',
    nav_profile: 'Профиль',
    nav_dashboard: 'Дашборд',
    nav_content: 'Контент',
    nav_quizzes: 'Тесттер',
    nav_submissions: 'Жұмыстар',
    nav_students: 'Оқушылар',
    nav_announcements: 'Хабарландырулар',

    desc_home: 'Дашборд шолуы',
    desc_subjects: 'Оқу жолдарын зерттеу',
    desc_assignments: 'Тапсырмалар мен жұмыстар',
    desc_feed: 'Қоғамдастық жаңалықтары',
    desc_chat: 'Хабарлар мен қолдау',
    desc_meetings: 'Сабақтар мен қоңыраулар',
    desc_profile: 'Жеке кеңістігіңіз',

    signin_title: 'Кіру',
    signin_subtitle: 'Қайта оралдыңыз! Оқуды жалғастыру үшін деректеріңізді енгізіңіз.',
    signin_phone_label: 'Телефон нөмірі немесе email',
    signin_pass_label: 'Пароль',
    signin_btn: 'Кіру',
    signin_loading: 'Кіру...',
    signin_first_time: 'Бірінші рет? Аккаунтты белсендіру →',
    signin_no_account: 'Аккаунт жоқ па?',
    signin_activate: 'Аккаунтты белсендіру',
    slide1_title: 'Бейнесабақтарды қараңыз',
    slide1_desc: 'Жоғары сапалы бейне контентпен өз қарқыныңызда үйреніңіз.',
    slide2_title: 'Білімді тексеріңіз',
    slide2_desc: 'Әр сабақтан кейін практикалық тесттер материалды бекітуге көмектеседі.',
    slide3_title: 'Прогресті бақылаңыз',
    slide3_desc: 'Прогресті бақылау, тапсырмалар және мұғалімдердің пікірлері арқылы оқу жолыңызды бақылаңыз.',

    register_title: 'Аккаунтты белсендіру',
    register_subtitle: 'Аккаунтты белсендіру үшін телефон нөмірін енгізіп, пароль жасаңыз.',
    register_phone_label: 'Телефон нөмірі',
    register_pass_label: 'Пароль жасау',
    register_btn: 'Белсендіру',
    register_loading: 'Белсендіру...',
    register_already: 'Белсендірілген бе?',
    register_signin: 'Кіру',
    register_join: 'Платформаға қосылыңыз',
    register_rocket_sub: 'Аккаунтты белсендіріп, оқу жолыңызды қазір бастаңыз.',

    profile_title: 'Менің профилім',
    profile_full_name: 'Толық аты',
    profile_phone: 'Телефон нөмірі',
    profile_email: 'Email',
    profile_save: 'Өзгерістерді сақтау',
    profile_saving: 'Сақталуда...',
    profile_saved: 'Профиль жаңартылды!',
    profile_upload_photo: 'Фото жүктеу',
    profile_change_photo: 'Фотоны өзгерту',
    profile_notifications: 'Хабарландырулар',
    profile_no_notif: 'Хабарландырулар жоқ.',
    profile_mark_read: 'Оқылды деп белгілеу',
    profile_mark_all: 'Барлығын оқылды деп белгілеу',

    teacher_panel: 'Мұғалім панелі',
    teacher_workspace: 'жұмыс кеңістігі',
    teacher_build: 'Жасау, басқару, оқыту',
    teacher_elegant: 'Заманауи мұғалімдерге арналған элегантты құралдар.',
    teacher_open_profile: 'Профильді ашу',
    teacher_exit: 'Панельден шығу',
    teacher_log_out: 'Шығу',
    teacher_active_section: 'Белсенді бөлім',
    teacher_premium: 'Премиум жұмыс кеңістігі',
    teacher_smart_flow: 'Ақылды оқыту процесі',
    teacher_manage_desc: 'Сабақтарды, тапсырмаларды, оқушыларды және хабарландыруларды бір әдемі кеңістікте басқарыңыз.',
    teacher_profile_label: 'МҰҒАЛІМ ПРОФИЛІ',

    student_os: 'ОҚУШЫ ОРТАСЫ',
    student_learn: 'Ақылдырақ оқы,',
    student_not_louder: 'қатты емес.',
    student_workspace_desc: 'Оқу, тапсырма тапсыру, кездесулерге қатысу және прогресті бақылауға арналған премиум кеңістік.',
    student_current_page: 'АҒЫМДАҒЫ БЕТ',
    student_focus: 'Фокус',
    student_focus_val: 'Жоғары',
    student_mode: 'Режим',
    student_mode_val: 'Оқушы',
    student_profile_label: 'ОҚУШЫ ПРОФИЛІ',
    student_welcome_back: 'Қайта оралдыңыз',
    student_learning_status: 'Оқу мәртебесі',
    student_submission_rate: 'Мақұлданған жұмыстарға негізделген табыс деңгейі.',
    student_total_submissions: 'Жалпы жұмыстар',
    student_approved: 'Мақұлданды',
    student_pending: 'Тексерілуде',
    student_rejected: 'Қабылданмады',
    student_recent_submissions: 'Соңғы жұмыстар',
    student_recent_sub_desc: 'Соңғы жүктелген тапсырмаларыңыз және олардың тексеру мәртебесі.',
    student_no_submissions: 'Жұмыстар жоқ.',
    student_profile_role: 'Профиль рөлі',
    student_account: 'Оқушы аккаунты',
    student_profile_role_desc: 'Бұл платформадағы жеке оқу сәйкестігіңіз. Бір жерден прогресті, жұмыстарды және белсенділікті бақылаңыз.',
    student_quick_summary: 'Қысқаша шолу',
    student_approved_work: 'Мақұлданған жұмыстар',
    student_pending_review: 'Тексерілуде',
    student_needs_correction: 'Түзету қажет',
    student_motivation: 'Мотивация',
    student_momentum: 'Импульсіңізді жалғастырыңыз',
    student_momentum_desc: 'Аяқталған әр жұмыс академиялық прогресіңізге қосылады. Тұрақты болыңыз.',
    student_recently_submitted: 'Жақында жіберілді',

    notifications_title: 'Хабарландырулар',
    notifications_empty: 'Хабарландырулар жоқ',
    notifications_mark_all: 'Барлығын оқылды деп белгілеу',

    status_approved: 'Мақұлданды',
    status_pending: 'Тексерілуде',
    status_rejected: 'Қабылданмады',
  },
}

export type TranslationKey = keyof typeof translations.en

interface LanguageContextType {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'ru',
  setLang: () => {},
  t: (key) => key,
})

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    return (localStorage.getItem('mls_lang') as Lang) || 'ru'
  })

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('mls_lang', l)
  }

  const t = (key: TranslationKey): string => {
    const dict = translations[lang] as Record<string, string>
    return dict[key] ?? (translations.en as Record<string, string>)[key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
